---
- name: Download release package
  get_url:
    url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "{{ cache_dir }}/golang.tar.gz"
    checksum: "{{ go_checksum }}"
  notify:
    - extract golang
    - install golang
    - install gopls

- name: Add to PATH
  copy:
    content: "export PATH=$PATH:{{ go_path }}/bin\n"
    dest: "{{ paths_dir }}/go_bin.sh"
