---
- name: extract golang
  unarchive:
    src: "{{ cache_dir }}/golang.tar.gz"
    dest: "{{ tools_dir }}"

- name: install gopls
  command: "{{ go_bin }}/go install golang.org/x/tools/gopls@latest"
