---
- name: extract neovim
  unarchive:
    src: "{{ cache_dir }}/nvim.tar.gz"
    dest: "{{ tools_dir }}"

- name: install neovim
  file:
    src: "{{ nvim_bin }}/nvim"
    dest: "{{ local_bin }}/{{ item }}"
    state: link
  with_items:
    - nvim
    - vim
