---
nvim_version: "v0.10.4"

nvim_releases_url: "https://github.com/neovim/neovim/releases/download"
nvim_tarball: "nvim-linux-x86_64.tar.gz"
nvim_bin: "nvim-linux-x86_64/bin"
nvim_cfg: "{{ ansible_env.HOME }}/.config/nvim"
