---
nvim_version: "v0.11.5"
nvim_checksum: "sha256:b2f91117be5b5ea39edd7297156dc2a4a8df4add6c95a90809a8df19e7ab6f52"

nvim_releases_url: "https://github.com/neovim/neovim/releases/download"
nvim_bin: "{{ tools_dir }}/nvim-linux-x86_64/bin"
nvim_cfg: "{{ ansible_env.HOME }}/.config/nvim"
