---
argument_specs:
  main:
    short_description: Installs Go for the current user
    options:
      go_version:
        default: "1.23.4"
      go_arch:
        default: "amd64"
      go_checksum:
        default: "sha256:6924efde5de86fe277676e929dc9917d466efa02fb934197bc2eba35d5680971"
      go_path:
        default: "{{ ansible_env.HOME }}/go"
      install_dir:
        default: "{{ ansible_env.HOME }}/.local"
      cache_dir:
        description: Staging location within the XDG cache directory
        default: "{{ ansible_env.HOME }}/.cache/dotfiles"
