#!/bin/bash

monitors=( $(xrandr | grep connected | grep -v disconnected | cut -d ' ' -f1) )

if [ ${#monitors[@]} -eq 2 ]; then
	# Set primary monitor
	primary=${monitors[1]} # eDP-1-1
	# set external monitor
	if [ ${#monitors[0]} -ne 0 ]; then
		external=${monitors[0]} # HDMI-0
	else
		external=${monitors[3]} # HDMI-1-1
	fi
	xrandr --output $primary --auto --primary --output $external --auto --right-of $primary
elif [ ${#monitors[@]} -gt 2 ]; then
	echo '[UNIMPLEMENTED] More than 1 external monitor detected.'
else
	echo 'No external monitor detected.'
fi
