---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ local_dir }}"
    - "{{ tools_dir }}"
    - "{{ paths_dir }}"
    - "{{ local_bin }}"

- name: Install bashrc
  copy:
    src: "bashrc"
    dest: "{{ ansible_env.HOME }}/.bashrc"

- name: Add local bin to PATH
  copy:
    content: "export PATH=$PATH:{{ local_bin }}\n"
    dest: "{{ paths_dir }}/local_bin.sh"

- name: Update apt cache
  become: true
  apt:
    update_cache: true
