---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ tools_dir }}"
    - "{{ tools_bin }}"

- name: Install dotfiles
  copy:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
  with_items:
    - { src: "bashrc", dest: ".bashrc" }
    - { src: "tmux.conf", dest: ".tmux.conf" }

- name: Install CLI utilities
  become: true
  apt:
    state: latest
    pkg:
      - tmux
      - git
