---
cache_dir: "{{ ansible_facts['env']['HOME'] }}/.cache/dotfiles"
local_dir: "{{ ansible_facts['env']['HOME'] }}/.local"
tools_dir: "{{ ansible_facts['env']['HOME'] }}/.tools"
paths_dir: "{{ local_dir }}/path.d"
local_bin: "{{ local_dir }}/bin"
