---
- name: "Download neovim {{ neovim_version }}"
  unarchive:
    src: "{{ nvim_releases_url }}/{{ nvim_version }}/{{ nvim_tarball }}"
    dest: "{{ tools_dir }}"
    remote_src: true
    creates: "{{ tools_dir }}/{{ nvim_bin }}/nvim"

- name: Install language servers
  apt:
    state: latest
    pkg:
      - clangd
      - gopls

- name: Install Python language server
  command:
    cmd: pip install -U jedi-language-server
    creates: "{{ ansible_env.HOME }}/.local/bin/jedi-language-server"

- name: Setup config files
  ansible.posix.synchronize:
    src: .
    dest: /home/user/.config/nvim
