---
- name: Download neovim
  unarchive:
    src: "{{ nvim_releases_url }}/{{ nvim_version }}/{{ nvim_tarball }}"
    dest: "{{ tools_dir }}"
    remote_src: true
    creates: "{{ tools_dir }}/{{ nvim_bin }}/nvim"

- name: Install neovim symlink
  file:
    src: "{{ tools_dir }}/{{ nvim_bin }}/nvim"
    dest: "{{ tools_bin }}/nvim"
    state: link

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nvim_cfg }}"
    - "{{ nvim_packpath }}"

- name: Setup config files
  copy:
    src: ./
    dest: "{{ nvim_cfg }}"

- name: Install LSP plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ nvim_packpath }}/lsp/start/{{ item.name }}"
  with_items:
    - { "name": "nvim-lspconfig", "repo": "https://github.com/neovim/nvim-lspconfig.git" }
    - { "name": "cmp-nvim-lsp", "repo": "https://github.com/hrsh7th/cmp-nvim-lsp.git" }
    - { "name": "nvim-cmp", "repo": "https://github.com/hrsh7th/nvim-cmp.git" }

- name: Install navigation plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ nvim_packpath }}/nav/{{ item.dest }}"
  with_items:
    - { "dest": "start/plenary.nvim", "repo": "https://github.com/nvim-lua/plenary.nvim.git" }
    - { "dest": "opt/telescope.nvim", "repo": "https://github.com/nvim-telescope/telescope.nvim.git" }

- name: Install colorscheme(s)
  git:
    repo: "{{ item.repo }}"
    dest: "{{ nvim_packpath }}/colo/opt/{{ item.name }}"
  with_items:
    - { "name": "moonfly", "repo": "https://github.com/bluz71/vim-moonfly-colors.git" }

- name: Install language servers
  become: true
  apt:
    state: latest
    pkg:
      - clangd
      - gopls

- name: Install Python language server
  command:
    cmd: pip install --user jedi-language-server
    creates: "{{ ansible_env.HOME }}/.local/bin/jedi-language-server"
